import type { Event } from "@/types/events";

export const SEED_EVENTS: Event[] = [
  {
    id: 1,
    title: "Vancouver International Children's Festival",
    description:
      "A week-long celebration of performing arts for young audiences featuring theatre, music, dance, and circus acts from around the world.",
    category: "family",
    start_date: "2026-05-25",
    end_date: "2026-05-31",
    start_time: "10:00",
    location: "Granville Island",
    city: "Vancouver",
    address: "1398 Cartwright St",
    url: null,
    image_url: null,
    is_free: false,
    price_info: "$12 per show, kids under 3 free",
    family_friendly: true,
    source_note: "Seed data",
    created_at: "2026-04-12T00:00:00Z",
    updated_at: "2026-04-12T00:00:00Z",
  },
  {
    id: 2,
    title: "Grouse Mountain Lumberjack Show",
    description:
      "Watch skilled lumberjacks compete in axe throwing, log rolling, and speed climbing. Fun for the whole family with stunning mountain views.",
    category: "outdoor",
    start_date: "2026-05-01",
    end_date: "2026-09-30",
    start_time: "12:00",
    location: "Grouse Mountain",
    city: "North Vancouver",
    address: "6400 Nancy Greene Way",
    url: null,
    image_url: null,
    is_free: false,
    price_info: "Included with Skyride admission",
    family_friendly: true,
    source_note: "Seed data",
    created_at: "2026-04-12T00:00:00Z",
    updated_at: "2026-04-12T00:00:00Z",
  },
  {
    id: 3,
    title: "Richmond Night Market",
    description:
      "BC's largest night market with over 600 international food stalls, games, shopping, and live entertainment. A summer staple for families.",
    category: "market",
    start_date: "2026-05-15",
    end_date: "2026-10-12",
    start_time: "19:00",
    location: "River Rock Casino Resort",
    city: "Richmond",
    address: "8811 River Rd",
    url: null,
    image_url: null,
    is_free: false,
    price_info: "$6.75 adult, kids under 8 free",
    family_friendly: true,
    source_note: "Seed data",
    created_at: "2026-04-12T00:00:00Z",
    updated_at: "2026-04-12T00:00:00Z",
  },
  {
    id: 4,
    title: "Bard on the Beach Shakespeare Festival",
    description:
      "Professional Shakespeare festival performed in tents on the waterfront with stunning mountain backdrop. Family-friendly matinees available.",
    category: "festival",
    start_date: "2026-06-03",
    end_date: "2026-09-20",
    start_time: "14:00",
    location: "Vanier Park",
    city: "Vancouver",
    address: "1695 Whyte Ave",
    url: null,
    image_url: null,
    is_free: false,
    price_info: "From $30, youth discounts available",
    family_friendly: true,
    source_note: "Seed data",
    created_at: "2026-04-12T00:00:00Z",
    updated_at: "2026-04-12T00:00:00Z",
  },
  {
    id: 5,
    title: "Burnaby Village Museum Free Admission Days",
    description:
      "Step back in time at this 1920s heritage village. Free admission days feature costumed interpreters, a working blacksmith, and vintage carousel rides.",
    category: "family",
    start_date: "2026-05-18",
    end_date: null,
    start_time: "11:00",
    location: "Burnaby Village Museum",
    city: "Burnaby",
    address: "6501 Deer Lake Ave",
    url: null,
    image_url: null,
    is_free: true,
    price_info: null,
    family_friendly: true,
    source_note: "Seed data",
    created_at: "2026-04-12T00:00:00Z",
    updated_at: "2026-04-12T00:00:00Z",
  },
  {
    id: 6,
    title: "Victoria Day Parade",
    description:
      "Annual parade celebrating Victoria Day with marching bands, floats, community groups, and performers winding through downtown Victoria.",
    category: "parade",
    start_date: "2026-05-18",
    end_date: null,
    start_time: "09:00",
    location: "Downtown Victoria",
    city: "Victoria",
    address: "Douglas Street",
    url: null,
    image_url: null,
    is_free: true,
    price_info: null,
    family_friendly: true,
    source_note: "Seed data",
    created_at: "2026-04-12T00:00:00Z",
    updated_at: "2026-04-12T00:00:00Z",
  },
  {
    id: 7,
    title: "Whistler Summer Concert Series",
    description:
      "Free outdoor concerts in Whistler Village every weekend featuring local and touring musicians. Bring a blanket and enjoy the mountain air.",
    category: "concert",
    start_date: "2026-06-14",
    end_date: "2026-08-30",
    start_time: "18:00",
    location: "Whistler Olympic Plaza",
    city: "Whistler",
    address: "4365 Blackcomb Way",
    url: null,
    image_url: null,
    is_free: true,
    price_info: null,
    family_friendly: true,
    source_note: "Seed data",
    created_at: "2026-04-12T00:00:00Z",
    updated_at: "2026-04-12T00:00:00Z",
  },
  {
    id: 8,
    title: "Kelowna Dragon Boat Festival",
    description:
      "Exciting dragon boat races on Okanagan Lake with food vendors, live music, and kids activities. A fun-filled day for the whole family.",
    category: "sports",
    start_date: "2026-06-20",
    end_date: "2026-06-21",
    start_time: "08:00",
    location: "Waterfront Park",
    city: "Kelowna",
    address: "1200 Water St",
    url: null,
    image_url: null,
    is_free: true,
    price_info: null,
    family_friendly: true,
    source_note: "Seed data",
    created_at: "2026-04-12T00:00:00Z",
    updated_at: "2026-04-12T00:00:00Z",
  },
];
